# Generated by Django 5.0.13 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyComplaint', models.TextField(verbose_name='Код нездужання')),
                ('Name', models.TextField(verbose_name='Нездужання')),
                ('IdUser', models.CharField(default='', max_length=100, verbose_name='код користувача')),
            ],
            options={
                'ordering': ['KeyComplaint'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KeyComplaint', models.TextField(verbose_name='Код нездужання')),
                ('KeyFeature', models.TextField(verbose_name='Код характера нездужання ')),
                ('Name', models.TextField(verbose_name='назва характера нездужання ')),
                ('IdUser', models.CharField(default='', max_length=100, verbose_name='код користувача')),
            ],
            options={
                'ordering': ['KeyComplaint'],
            },
        ),
    ]
